title: Andrew Sayre
email: "andrew@andrewsayre.com"
description: ""
author: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - one-page-wonder.gif

# Social Profiles
twitter_username: "dgtldilemma"
github_username: "andrewsayre"
facebook_username: "digitaldilemma"
